#!/bin/sh

#PBS -q WD
#PBS -N PBS_trial
#PBS -l select=1:ncpus=3
#PBS -l walltime=0:30:00
#PBS -m abe
#PBS -M eliransh@ariel.ac.il


module load gcc openmpi hdf5/serial python/3
source /home/eliransc/projects/def-dkrass/eliransc/mom_match/bin/activate
mpirun python3 //home/elirans/project/transient_inv/code/inventory_simpy_ph.py --dynamic-demand --n-settings 454 --replications 110000 --horizon 100 --inv-dir /home/elirans/scratch/elad_trans/training_data/inv_level --order-dir /home/elirans/scratch/elad_trans/training_data/order --loss-dir /home/elirans/scratch/elad_trans/training_data/loss

